-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_GovernmentContractDiscovery" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "google_query" TEXT NOT NULL,
    "service_category" TEXT,
    "title" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "domain" TEXT NOT NULL,
    "snippet" TEXT,
    "document_type" TEXT,
    "notice_id" TEXT,
    "solicitation_number" TEXT,
    "agency" TEXT,
    "naics_codes" TEXT NOT NULL DEFAULT '[]',
    "set_aside" TEXT NOT NULL DEFAULT '[]',
    "location_mentions" TEXT NOT NULL DEFAULT '[]',
    "detected_keywords" TEXT NOT NULL DEFAULT '[]',
    "relevance_score" INTEGER NOT NULL DEFAULT 0,
    "ingestion_status" TEXT NOT NULL DEFAULT 'discovered',
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "verified_at" DATETIME,
    "verified_by" TEXT,
    "downloaded" BOOLEAN NOT NULL DEFAULT false,
    "downloaded_at" DATETIME,
    "proposal_generated" BOOLEAN NOT NULL DEFAULT false,
    "proposal_generated_at" DATETIME,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    "discovered_by" TEXT,
    "ingestion_source" TEXT,
    "ingestion_batch_id" TEXT,
    "flagged" BOOLEAN NOT NULL DEFAULT false,
    "flagged_at" DATETIME,
    "flagged_by" TEXT,
    "ignored" BOOLEAN NOT NULL DEFAULT false,
    "raw_payload" TEXT,
    "normalized_fields" TEXT,
    "source_queries" TEXT NOT NULL DEFAULT '[]',
    "ingested_at" DATETIME,
    "scraped" BOOLEAN NOT NULL DEFAULT false,
    "scraped_at" DATETIME,
    "scraped_html_content" TEXT,
    "scraped_text_content" TEXT,
    "sow_attachment_url" TEXT,
    "sow_attachment_type" TEXT,
    "sow_attachment_content" TEXT,
    "sow_scraped" BOOLEAN NOT NULL DEFAULT false,
    "sow_scraped_at" DATETIME,
    "analysis_summary" TEXT,
    "analysis_confidence" REAL,
    "analysis_keywords" TEXT NOT NULL DEFAULT '[]',
    "aiParsedData" TEXT,
    "aiParsedAt" DATETIME,
    "aiSummary" TEXT,
    "aiKeyRequirements" TEXT,
    "aiKeywords" TEXT,
    "aiStrengths" TEXT,
    "aiConcerns" TEXT,
    "aiFitScore" REAL,
    "aiServiceCategory" TEXT,
    "aiRecommendedActions" TEXT,
    "aiAnalysisGeneratedAt" DATETIME,
    "aiAnalysis" TEXT,
    "aiAwardLikelihood" REAL,
    "aiAwardConfidence" TEXT,
    "aiAwardReasoning" TEXT,
    "aiAwardStrengths" TEXT,
    "aiAwardConcerns" TEXT,
    "aiAwardRiskFactors" TEXT,
    "aiAwardRecommendations" TEXT,
    "aiAwardLikelihoodGeneratedAt" DATETIME,
    "dismissed" BOOLEAN NOT NULL DEFAULT false,
    "dismissed_at" DATETIME,
    "dismissed_by" TEXT,
    "dismissal_reason" TEXT,
    "points_of_contact" TEXT,
    "description" TEXT,
    "requirements" TEXT,
    "deadline" TEXT,
    "estimated_value" TEXT,
    "period_of_performance" TEXT,
    "place_of_performance" TEXT
);
INSERT INTO "new_GovernmentContractDiscovery" ("agency", "aiAnalysisGeneratedAt", "aiAwardConcerns", "aiAwardConfidence", "aiAwardLikelihood", "aiAwardLikelihoodGeneratedAt", "aiAwardReasoning", "aiAwardRecommendations", "aiAwardRiskFactors", "aiAwardStrengths", "aiConcerns", "aiFitScore", "aiKeyRequirements", "aiKeywords", "aiParsedAt", "aiParsedData", "aiRecommendedActions", "aiServiceCategory", "aiStrengths", "aiSummary", "analysis_confidence", "analysis_keywords", "analysis_summary", "created_at", "deadline", "description", "detected_keywords", "discovered_by", "dismissal_reason", "dismissed", "dismissed_at", "dismissed_by", "document_type", "domain", "downloaded", "downloaded_at", "estimated_value", "flagged", "flagged_at", "flagged_by", "google_query", "id", "ingestion_batch_id", "ingestion_source", "ingestion_status", "location_mentions", "naics_codes", "notice_id", "period_of_performance", "place_of_performance", "points_of_contact", "proposal_generated", "proposal_generated_at", "relevance_score", "requirements", "scraped", "scraped_at", "scraped_html_content", "scraped_text_content", "service_category", "set_aside", "snippet", "solicitation_number", "sow_attachment_content", "sow_attachment_type", "sow_attachment_url", "sow_scraped", "sow_scraped_at", "title", "updated_at", "url", "verified", "verified_at", "verified_by") SELECT "agency", "aiAnalysisGeneratedAt", "aiAwardConcerns", "aiAwardConfidence", "aiAwardLikelihood", "aiAwardLikelihoodGeneratedAt", "aiAwardReasoning", "aiAwardRecommendations", "aiAwardRiskFactors", "aiAwardStrengths", "aiConcerns", "aiFitScore", "aiKeyRequirements", "aiKeywords", "aiParsedAt", "aiParsedData", "aiRecommendedActions", "aiServiceCategory", "aiStrengths", "aiSummary", "analysis_confidence", "analysis_keywords", "analysis_summary", "created_at", "deadline", "description", "detected_keywords", "discovered_by", "dismissal_reason", "dismissed", "dismissed_at", "dismissed_by", "document_type", "domain", "downloaded", "downloaded_at", "estimated_value", "flagged", "flagged_at", "flagged_by", "google_query", "id", "ingestion_batch_id", "ingestion_source", "ingestion_status", "location_mentions", "naics_codes", "notice_id", "period_of_performance", "place_of_performance", "points_of_contact", "proposal_generated", "proposal_generated_at", "relevance_score", "requirements", "scraped", "scraped_at", "scraped_html_content", "scraped_text_content", "service_category", "set_aside", "snippet", "solicitation_number", "sow_attachment_content", "sow_attachment_type", "sow_attachment_url", "sow_scraped", "sow_scraped_at", "title", "updated_at", "url", "verified", "verified_at", "verified_by" FROM "GovernmentContractDiscovery";
DROP TABLE "GovernmentContractDiscovery";
ALTER TABLE "new_GovernmentContractDiscovery" RENAME TO "GovernmentContractDiscovery";
CREATE UNIQUE INDEX "GovernmentContractDiscovery_url_key" ON "GovernmentContractDiscovery"("url");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
